name: Playwright & API Tests

on: [push, pull_request]  # Run tests on every push and PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          playwright install

      - name: Run Playwright UI Tests
        run: |
          source venv/bin/activate
          pytest tests/test_example.py --alluredir=allure-results

      - name: Run API Tests
        run: |
          source venv/bin/activate
          pytest tests/test_api.py --alluredir=allure-results

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
